on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 🚀 Publish preview
        run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive
        env:
          USERPOOL_ID: ${{ secrets.UserPoolId }}
          CLIENT_ID: ${{ secrets.ClientId }}
          API_URL: ${{ secrets.ApiURL }}

      - name: 💬 Comment preview
        uses: expo/expo-github-action/preview-comment@v7
        with:
          channel: pr-${{ github.event.number }}
